version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./k8s/Dockerfile
      target: prod
    image: auth_jit:${AUTH_JIT_VERSION:-latest}
    restart: always
    env_file:
    - .env
    environment:
      AUTH_JIT_HOST: 0.0.0.0
